package View;

import Clubes_Campeonatos.Campeonato;
import Clubes_Campeonatos.Clube;
import Clubes_Campeonatos.Clubes_Campeonatos;
import Clubes_Campeonatos.Jogador;
import Clubes_Campeonatos.Jogadores_Jogo;
import Clubes_Campeonatos.Jogo;
import Clubes_Campeonatos.Utils;
import Controller.ServicoBancoCampeonato;
import Controller.ServicoBancoClube;
import Controller.ServicoBancoClubeCampeonato;
import Controller.ServicoBancoJogador;
import Controller.ServicoBancoJogadoresJogo;
import Controller.ServicoBancoJogo;
import java.awt.TextField;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class Cadastro_Jogo extends javax.swing.JFrame {

    Utils utils = new Utils();
    Cadastro_Clube cadastro_Clube;
    ServicoBancoCampeonato sbcam = new ServicoBancoCampeonato();
    ServicoBancoClubeCampeonato sbcc = new ServicoBancoClubeCampeonato();
    ServicoBancoClube sbc = new ServicoBancoClube();
    ServicoBancoJogo sbj = new ServicoBancoJogo();
    ServicoBancoJogador sbjogador = new ServicoBancoJogador();
    ServicoBancoJogadoresJogo sbjj = new ServicoBancoJogadoresJogo();
    Campeonato campeonato = new Campeonato();
    Clube clube = new Clube();
    Clube clubee;
    Jogo jogo;
    Jogador jogador;
    Clubes_Campeonatos clubes_Campeonatos;
    Jogadores_Jogo jogadores, jogador1, jogador2, jogador3, jogador4, jogador5, jogador6, jogador7, jogador8, jogador9;
    int coda, codb, codc, codd, code, codf, codg, codh, codi, codj = 0;
    int clubeTemp = 0;

    public Cadastro_Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbDiaJogo = new javax.swing.JLabel();
        LbHoraJogo = new javax.swing.JLabel();
        CheckCartaoVermelhorJogadorFora1 = new javax.swing.JCheckBox();
        TxtHoraJogo = new javax.swing.JFormattedTextField();
        TxtDiaJogo = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtGolJogador2 = new javax.swing.JTextField();
        JComboJogadorCasa = new javax.swing.JComboBox<>();
        TxtGolJogador3 = new javax.swing.JTextField();
        JComboJogadorFora = new javax.swing.JComboBox<>();
        TxtGolJogador4 = new javax.swing.JTextField();
        LbPlacarMandante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LbPlacarVisitante = new javax.swing.JTextField();
        TxtCartaoJogador1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtCartaoJogador2 = new javax.swing.JTextField();
        TxtCartaoJogador3 = new javax.swing.JTextField();
        TxtGolJogador = new javax.swing.JTextField();
        TxtCartaoJogador4 = new javax.swing.JTextField();
        ComboClube = new javax.swing.JComboBox<>();
        TxtCartaoJogador = new javax.swing.JTextField();
        ComboClube1 = new javax.swing.JComboBox<>();
        CheckCartaoVermelhorJogador = new javax.swing.JCheckBox();
        LbLocalJogo = new javax.swing.JLabel();
        TxtLocalJogo = new javax.swing.JTextField();
        JbtnSalvar = new javax.swing.JButton();
        JBtnSair = new javax.swing.JButton();
        JBtnLimpar = new javax.swing.JButton();
        TxtNovoClubeMandante = new javax.swing.JButton();
        TxtNovoClube1 = new javax.swing.JButton();
        CheckCartaoVermelhorJogador1 = new javax.swing.JCheckBox();
        CheckCartaoVermelhorJogador2 = new javax.swing.JCheckBox();
        CheckCartaoVermelhorJogador3 = new javax.swing.JCheckBox();
        CheckCartaoVermelhorJogador4 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CheckCartaoVermelhorJogadorFora2 = new javax.swing.JCheckBox();
        TxtJogadorFora2 = new javax.swing.JTextField();
        CheckCartaoVermelhorJogadorFora3 = new javax.swing.JCheckBox();
        TxtJogadorFora1 = new javax.swing.JTextField();
        CheckCartaoVermelhorJogadorFora4 = new javax.swing.JCheckBox();
        TxtJogadorFora3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtJogadorFora4 = new javax.swing.JTextField();
        TxtGolFora1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtGolFora2 = new javax.swing.JTextField();
        TxtGolFora3 = new javax.swing.JTextField();
        TxtGolFora4 = new javax.swing.JTextField();
        TxtCartaoFora1 = new javax.swing.JTextField();
        TxtCartaoFora2 = new javax.swing.JTextField();
        TxtCartaoFora3 = new javax.swing.JTextField();
        TxtCartaoFora4 = new javax.swing.JTextField();
        LbMandante = new javax.swing.JLabel();
        TxtCartaoFora = new javax.swing.JTextField();
        LbVisitante = new javax.swing.JLabel();
        CheckCartaoVermelhorJogadorFora = new javax.swing.JCheckBox();
        TxtJogador = new javax.swing.JTextField();
        TxtGolFora = new javax.swing.JTextField();
        LbJogadores = new javax.swing.JLabel();
        TxtJogadorFora = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        LbJogadores1 = new javax.swing.JLabel();
        TxtJogador1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        TxtJogador2 = new javax.swing.JTextField();
        TxtJogador3 = new javax.swing.JTextField();
        TxtJogador4 = new javax.swing.JTextField();
        TxtGolJogador1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LbCat = new javax.swing.JLabel();
        ComboCampeonato = new javax.swing.JComboBox<>();
        JrFimPartida = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        LbDiaJogo.setText("DIA DO JOGO");

        LbHoraJogo.setText("HORA DO JOGO");

        try {
            TxtHoraJogo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TxtDiaJogo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("PLACAR FINAL");

        JComboJogadorCasa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboJogadorCasaItemStateChanged(evt);
            }
        });
        JComboJogadorCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JComboJogadorCasaMouseClicked(evt);
            }
        });

        JComboJogadorFora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JComboJogadorForaMouseClicked(evt);
            }
        });

        LbPlacarMandante.setEditable(false);
        LbPlacarMandante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbPlacarMandante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LbPlacarMandante.setText("0");
        LbPlacarMandante.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/goal-full-icon.png"))); // NOI18N

        LbPlacarVisitante.setEditable(false);
        LbPlacarVisitante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbPlacarVisitante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LbPlacarVisitante.setText("0");
        LbPlacarVisitante.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TxtCartaoJogador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCartaoJogador1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoJogador1FocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("X");

        TxtCartaoJogador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCartaoJogador2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoJogador2FocusLost(evt);
            }
        });

        TxtCartaoJogador3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCartaoJogador3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoJogador3FocusLost(evt);
            }
        });

        TxtGolJogador.setColumns(1);
        TxtGolJogador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        TxtCartaoJogador4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCartaoJogador4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoJogador4FocusLost(evt);
            }
        });

        ComboClube.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ComboClube.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboClubeItemStateChanged(evt);
            }
        });

        TxtCartaoJogador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCartaoJogador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoJogadorFocusLost(evt);
            }
        });

        ComboClube1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ComboClube1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboClube1ItemStateChanged(evt);
            }
        });

        CheckCartaoVermelhorJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCartaoVermelhorJogadorActionPerformed(evt);
            }
        });

        LbLocalJogo.setText("LOCAL DO JOGO");

        TxtLocalJogo.setMaximumSize(new java.awt.Dimension(35, 16));
        TxtLocalJogo.setMinimumSize(new java.awt.Dimension(35, 16));

        JbtnSalvar.setText("SALVAR");
        JbtnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JbtnSalvarMouseClicked(evt);
            }
        });

        JBtnSair.setText("SAIR");
        JBtnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtnSairMouseClicked(evt);
            }
        });

        JBtnLimpar.setText("LIMPAR");
        JBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLimparActionPerformed(evt);
            }
        });

        TxtNovoClubeMandante.setText("+");
        TxtNovoClubeMandante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtNovoClubeMandanteMouseClicked(evt);
            }
        });

        TxtNovoClube1.setText("+");
        TxtNovoClube1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtNovoClube1MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon_Amarelo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon_Vermelho (2).png"))); // NOI18N

        TxtJogadorFora2.setEditable(false);

        TxtJogadorFora1.setEditable(false);

        TxtJogadorFora3.setEditable(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon_Amarelo.png"))); // NOI18N
        jLabel5.setText("jLabel3");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TxtJogadorFora4.setEditable(false);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon_Vermelho (2).png"))); // NOI18N

        TxtCartaoFora1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoFora1FocusLost(evt);
            }
        });

        TxtCartaoFora2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoFora2FocusLost(evt);
            }
        });

        TxtCartaoFora3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoFora3FocusLost(evt);
            }
        });

        TxtCartaoFora4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoFora4FocusLost(evt);
            }
        });

        LbMandante.setText("TIME MANDANTE");

        TxtCartaoFora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCartaoForaFocusLost(evt);
            }
        });

        LbVisitante.setText("TIME VISITANTE");

        TxtJogador.setEditable(false);

        LbJogadores.setText("JOGADORES!");

        TxtJogadorFora.setEditable(false);

        jTextField2.setText("jTextField1");

        LbJogadores1.setText("JOGADORES!");

        TxtJogador1.setEditable(false);

        jTextField3.setText("jTextField1");

        TxtJogador2.setEditable(false);

        TxtJogador3.setEditable(false);

        TxtJogador4.setEditable(false);

        jLabel1.setFont(new java.awt.Font("MingLiU-ExtB", 0, 18)); // NOI18N
        jLabel1.setText("CADASTRAR JOGOS...");

        LbCat.setText("CAMPEONATO");

        ComboCampeonato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCampeonatoItemStateChanged(evt);
            }
        });

        JrFimPartida.setText("FINAL DA PARTIDA");
        JrFimPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JrFimPartidaMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/View/goal-full-icon.png")))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbHoraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbDiaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(276, 276, 276)
                                .addComponent(TxtDiaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(LbMandante, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(301, 301, 301)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtHoraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(LbCat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(JbtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(JBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addComponent(JBtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(LbLocalJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(TxtLocalJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtNovoClubeMandante)
                                .addGap(8, 8, 8)
                                .addComponent(ComboClube, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LbJogadores)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtCartaoJogador1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCartaoJogador2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCartaoJogador3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCartaoJogador4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCartaoJogador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addComponent(JComboJogadorCasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckCartaoVermelhorJogador)
                            .addComponent(CheckCartaoVermelhorJogador1)
                            .addComponent(CheckCartaoVermelhorJogador2)
                            .addComponent(CheckCartaoVermelhorJogador3)
                            .addComponent(CheckCartaoVermelhorJogador4)
                            .addComponent(jLabel4))
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JComboJogadorFora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(LbJogadores1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtJogadorFora1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolFora1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtJogadorFora2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolFora2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtJogadorFora3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolFora3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtJogadorFora4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolFora4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtJogadorFora, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtGolFora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtCartaoFora1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCartaoFora2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCartaoFora3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCartaoFora4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCartaoFora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtNovoClube1)
                                .addGap(8, 8, 8)
                                .addComponent(ComboClube1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckCartaoVermelhorJogadorFora)
                            .addComponent(CheckCartaoVermelhorJogadorFora1)
                            .addComponent(CheckCartaoVermelhorJogadorFora2)
                            .addComponent(CheckCartaoVermelhorJogadorFora3)
                            .addComponent(CheckCartaoVermelhorJogadorFora4)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JrFimPartida)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbPlacarMandante, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbPlacarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDiaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDiaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbHoraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtHoraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbMandante)
                    .addComponent(LbVisitante))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNovoClubeMandante)
                    .addComponent(ComboClube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNovoClube1)
                    .addComponent(ComboClube1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbJogadores)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtGolJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtGolJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtGolJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtGolJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtGolJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtCartaoJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckCartaoVermelhorJogador))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TxtCartaoJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CheckCartaoVermelhorJogador1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtCartaoJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(CheckCartaoVermelhorJogador2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCartaoJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CheckCartaoVermelhorJogador3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtCartaoJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckCartaoVermelhorJogador4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LbJogadores1)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtJogadorFora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtGolFora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtJogadorFora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtGolFora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtJogadorFora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtGolFora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtJogadorFora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtGolFora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtJogadorFora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtGolFora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtCartaoFora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckCartaoVermelhorJogadorFora))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TxtCartaoFora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CheckCartaoVermelhorJogadorFora1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtCartaoFora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(CheckCartaoVermelhorJogadorFora2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCartaoFora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CheckCartaoVermelhorJogadorFora3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtCartaoFora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckCartaoVermelhorJogadorFora4))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JComboJogadorCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(JrFimPartida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbPlacarMandante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbPlacarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbLocalJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtLocalJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JComboJogadorFora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogadoresCasa() {
        TxtJogador.setText("");
        TxtJogador1.setText("");
        TxtJogador2.setText("");
        TxtJogador3.setText("");
        TxtJogador4.setText("");
    }

    private void jogadoresFora() {
        TxtJogadorFora.setText("");
        TxtJogadorFora1.setText("");
        TxtJogadorFora2.setText("");
        TxtJogadorFora3.setText("");
        TxtJogadorFora4.setText("");
    }

    public void clearSc() {
        if (ComboCampeonato.isDisplayable()) {
            ComboCampeonato.setSelectedIndex(-1);
        }
        TxtDiaJogo.setText("");
        TxtHoraJogo.setText("");
        utils.setGols(TxtGolFora, TxtGolFora1, TxtGolFora2, TxtGolFora3, TxtGolFora4, TxtGolJogador, TxtGolJogador1, TxtGolJogador2, TxtGolJogador3, TxtGolJogador4);
        utils.setCartoes(TxtCartaoFora1, TxtCartaoFora2, TxtCartaoFora3, TxtCartaoFora4, TxtCartaoFora, TxtCartaoJogador, TxtCartaoJogador1, TxtCartaoJogador2, TxtCartaoJogador3, TxtCartaoJogador4);
        LbPlacarMandante.setText("");
        LbPlacarVisitante.setText("");
        if (ComboClube.isDisplayable()) {
            ComboClube.setSelectedIndex(-1);
        }
        this.jogadoresCasa();
        if (ComboClube1.isDisplayable()) {
            ComboClube1.setSelectedIndex(-1);
        }
        this.jogadoresFora();
        TxtLocalJogo.setText("");
        JBtnLimpar.setEnabled(false);

    }

    private void JComboJogadorCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JComboJogadorCasaMouseClicked

        if (JComboJogadorCasa.getItemCount() <= 0) {
            return;
        }
        if (JComboJogadorCasa.getSelectedIndex() < 0) {
            return;
        }
        Jogador jogador = (Jogador) JComboJogadorCasa.getSelectedItem();
        try {
            assert jogador != null;
            sbjogador.update(jogador);
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (TxtJogador.getText().isBlank()) {
            TxtJogador.setText(jogador.getNome());
            coda = jogador.getCodigo();

        } else if (TxtJogador1.getText().isBlank()) {
            TxtJogador1.setText(jogador.getNome());
            codb = jogador.getCodigo();

        } else if (TxtJogador2.getText().isBlank()) {
            TxtJogador2.setText(jogador.getNome());
            codc = jogador.getCodigo();
        } else if (TxtJogador3.getText().isBlank()) {
            TxtJogador3.setText(jogador.getNome());
            codd = jogador.getCodigo();
        } else {
            TxtJogador4.setText(jogador.getNome());
            code = jogador.getCodigo();
        }
        JComboJogadorCasa.setSelectedIndex(-1);
    }//GEN-LAST:event_JComboJogadorCasaMouseClicked

    private void ComboClubeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboClubeItemStateChanged

        if (ComboClube.getItemCount() <= 0) {
            return;
        }
        if (ComboClube.getSelectedIndex() < 0) {
            return;
        }
        Clube clube = (Clube) ComboClube.getSelectedItem();
        assert clube != null;
        try {
            utils.atualizarJogadoor(JComboJogadorCasa, sbjogador, clube.getCodigo());
//            this.atualizarClubeTabela(clube.getCodigo());
//            sbcc.getDadosByClube(code)
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboClubeItemStateChanged

    private void ComboClube1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboClube1ItemStateChanged
        if (ComboClube1.getItemCount() <= 0) {
            return;
        }
        if (ComboClube1.getSelectedIndex() < 0) {
            return;
        }
        Clube clube = (Clube) ComboClube1.getSelectedItem();
        assert clube != null;
        try {
            utils.atualizarJogadoor(JComboJogadorFora, sbjogador, clube.getCodigo());
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
//        atualizarClubeTabela();

    }//GEN-LAST:event_ComboClube1ItemStateChanged

    public int cartaoVermelho(JCheckBox cart) {
        int cartao = 0;
        if (cart.isEnabled()) {
            cartao = 1;
        }

        return cartao;
    }

    public int cadastrarOuAtualizar(int codClube, int codCam) {
        int clube_codigo = 0;
        try {
            if (codClube == sbcc.getDadosByClube(codClube).getCodClube()) {
                atualizarClubeTabela(codClube);
            } else {
                cadastrarClubeCampeonato(codClube, codCam);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Utils.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    public int cadastrarOuAtualizarVisitante(int codClube, int codCam) {
        int clube_codigo = 0;
        try {
            if (codClube == sbcc.getDadosByClube(codClube).getCodClube()) {
                atualizarClubeVisitanteTabela(codClube);
            } else {
                cadastrarClubeCampeonatoVisitante(codClube, codCam);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Utils.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    public void cadastrarClubeCampeonato(int codClube, int codCampeonato) {
        int vitorias = utils.vitoriasMandante(LbPlacarMandante, LbPlacarVisitante);
        int empates = utils.empate(LbPlacarMandante, LbPlacarVisitante);
        int derrotas = utils.derrota(vitorias, LbPlacarMandante, LbPlacarVisitante);
        int cartoesAmarelo = utils.amarelos(TxtCartaoJogador, TxtCartaoJogador1, TxtCartaoJogador2, TxtCartaoJogador3, TxtCartaoJogador4);
        int cartoesVermelho = utils.vermelhos(CheckCartaoVermelhorJogador, CheckCartaoVermelhorJogador1, CheckCartaoVermelhorJogador2, CheckCartaoVermelhorJogador3, CheckCartaoVermelhorJogador4);
        if (codClube > 0 && codCampeonato > 0) {
            try {
                clubes_Campeonatos = new Clubes_Campeonatos(codClube, codCampeonato, vitorias, derrotas, empates, Integer.parseInt(LbPlacarMandante.getText()), Integer.parseInt(LbPlacarVisitante.getText()), cartoesAmarelo, cartoesVermelho);
                sbcc.insert(clubes_Campeonatos);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public void cadastrarClubeCampeonatoVisitante(int codClube, int codCampeonato) {
        int vitorias = utils.vitoriasMandante(LbPlacarVisitante, LbPlacarMandante);
        int empates = utils.empate(LbPlacarMandante, LbPlacarVisitante);
        int derrotas = utils.derrota(vitorias, LbPlacarVisitante, LbPlacarMandante);
        int cartoesAmarelo = utils.amarelos(TxtCartaoFora, TxtCartaoFora1, TxtCartaoFora2, TxtCartaoFora3, TxtCartaoFora4);
        int cartoesVermelho = utils.vermelhos(CheckCartaoVermelhorJogadorFora, CheckCartaoVermelhorJogadorFora1, CheckCartaoVermelhorJogadorFora2, CheckCartaoVermelhorJogadorFora3, CheckCartaoVermelhorJogadorFora4);

        if (codClube > 0 && codCampeonato > 0) {
            try {
                clubes_Campeonatos = new Clubes_Campeonatos(codClube, codCampeonato, vitorias, derrotas, empates, Integer.parseInt(LbPlacarVisitante.getText()), Integer.parseInt(LbPlacarMandante.getText()), cartoesAmarelo, cartoesVermelho);
                sbcc.insert(clubes_Campeonatos);

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public void atualizarClubeTabela(int codClube) {
        int cod;
        int vitoria = utils.vitoriasMandante(LbPlacarMandante, LbPlacarVisitante);
        int derrota = utils.derrota(vitoria, LbPlacarMandante, LbPlacarVisitante);
        int empate = utils.empate(LbPlacarMandante, LbPlacarVisitante);
        int golP = Integer.parseInt(LbPlacarMandante.getText());
        int golC = Integer.parseInt(LbPlacarVisitante.getText());
        int car_A = utils.amarelos(TxtCartaoJogador, TxtCartaoJogador1, TxtCartaoJogador2, TxtCartaoJogador3, TxtCartaoJogador4);
        int car_v = utils.vermelhos(CheckCartaoVermelhorJogador, CheckCartaoVermelhorJogador1, CheckCartaoVermelhorJogador2, CheckCartaoVermelhorJogador3, CheckCartaoVermelhorJogador4);
        int camp;
        try {
            cod = sbcc.getDadosByClube(codClube).getCodigo();
            vitoria += sbcc.getDadosByClube(codClube).getVitorias();
            derrota += sbcc.getDadosByClube(codClube).getDerrotas();
            empate += sbcc.getDadosByClube(codClube).getEmpates();
            golP += sbcc.getDadosByClube(codClube).getGolsPro();
            golC += sbcc.getDadosByClube(codClube).getGolsContra();
            car_A += sbcc.getDadosByClube(codClube).getCartoesAmarelo();
            car_v += sbcc.getDadosByClube(codClube).getCartoesVermelho();
            camp = sbcc.getDadosByClube(codClube).getCodCampeonato();

            clubes_Campeonatos = new Clubes_Campeonatos(cod, codClube, camp, vitoria, derrota, empate, golP, golC, car_A, car_v);
            sbcc.update(clubes_Campeonatos);

        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void atualizarClubeVisitanteTabela(int codClube) {
        int cod;
        int vitoria = utils.vitoriasMandante(LbPlacarVisitante, LbPlacarMandante);
        int derrota = utils.derrota(vitoria, LbPlacarVisitante, LbPlacarMandante);
        int empate = utils.empate(LbPlacarMandante, LbPlacarVisitante);
        int golP = Integer.parseInt(LbPlacarVisitante.getText());
        int golC = Integer.parseInt(LbPlacarMandante.getText());
        int car_A = utils.amarelos(TxtCartaoFora, TxtCartaoFora1, TxtCartaoFora2, TxtCartaoFora3, TxtCartaoFora4);
        int car_v = utils.vermelhos(CheckCartaoVermelhorJogadorFora, CheckCartaoVermelhorJogadorFora1, CheckCartaoVermelhorJogadorFora2, CheckCartaoVermelhorJogadorFora3, CheckCartaoVermelhorJogadorFora4);
        int camp;

        try {
            cod = sbcc.getDadosByClube(codClube).getCodigo();

            vitoria += sbcc.getDadosByClube(codClube).getVitorias();
            derrota += sbcc.getDadosByClube(codClube).getDerrotas();
            empate += sbcc.getDadosByClube(codClube).getEmpates();
            golP += sbcc.getDadosByClube(codClube).getGolsPro();
            golC += sbcc.getDadosByClube(codClube).getGolsContra();
            car_A += sbcc.getDadosByClube(codClube).getCartoesAmarelo();
            car_v += sbcc.getDadosByClube(codClube).getCartoesVermelho();
            camp = sbcc.getDadosByClube(codClube).getCodCampeonato();

            clubes_Campeonatos = new Clubes_Campeonatos(cod, codClube, camp, vitoria, derrota, empate, golP, golC, car_A, car_v);
            sbcc.update(clubes_Campeonatos);

        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void JbtnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbtnSalvarMouseClicked
        if (TxtDiaJogo.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Informe uma data valida!");
            TxtDiaJogo.setText(utils.converterData());
            return;
        }
        if (TxtHoraJogo.getText().isBlank()) {
            Date hora = new Date();
            JOptionPane.showMessageDialog(null, "Informe um horário valido!");
            TxtHoraJogo.setText(utils.converterHora());
            return;

        }
        if (TxtGolJogador.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe A quantidade de gols marcados!");
            TxtGolJogador.requestFocus();
            return;
        }

        if (TxtLocalJogo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Local do Jogo!");
            TxtLocalJogo.requestFocus();
            return;
        }
        try {
            if (ComboClube.getSelectedIndex() >= 0 && ComboClube1.getSelectedIndex() >= 0) {

                Clube clube = (Clube) ComboClube.getSelectedItem();
                assert clube != null;
                clube.setNome(ComboClube.getSelectedItem().toString());
                sbc.update(clube);
                clubeTemp = clube.getCodigo();

                clubee = (Clube) ComboClube1.getSelectedItem();
                assert clubee != null;
                clubee.setNome(ComboClube1.getSelectedItem().toString());
                sbc.update(clubee);

                int codJogo = 0;
                if (ComboCampeonato.getSelectedIndex() >= 0) {
                    Campeonato campeonato = (Campeonato) ComboCampeonato.getSelectedItem();
                    assert campeonato != null;
                    campeonato.setNome(ComboCampeonato.getSelectedItem().toString());
                    sbcam.update(campeonato);
                    jogo = new Jogo(campeonato.getCodigo(), utils.strToDate(TxtDiaJogo.getText()), utils.strToTime(TxtHoraJogo.getText()), clubeTemp, Integer.parseInt(LbPlacarMandante.getText()), clubee.getCodigo(), Integer.parseInt(LbPlacarVisitante.getText()), TxtLocalJogo.getText());
                    sbj.insert(jogo);
                    codJogo = jogo.getCodigo();
                    cadastrarOuAtualizar(clubeTemp, campeonato.getCodigo());
                    cadastrarOuAtualizarVisitante(clubee.getCodigo(), campeonato.getCodigo());

                }

                Jogadores_Jogo jogadores = new Jogadores_Jogo(Integer.parseInt(TxtGolJogador.getText()), Integer.parseInt(TxtCartaoJogador.getText()), cartaoVermelho(CheckCartaoVermelhorJogador), coda, codJogo);
                sbjj.insert(jogadores);
//                Jogadores_Jogo jogador1 = new Jogadores_Jogo(Integer.parseInt(TxtGolJogador1.getText()), Integer.parseInt(TxtCartaoJogador1.getText()), cartaoVermelho(CheckCartaoVermelhorJogador1), codb, codJogo);
//                sbjj.insert(jogador1);
//                Jogadores_Jogo jogador2 = new Jogadores_Jogo(Integer.parseInt(TxtGolJogador2.getText()), Integer.parseInt(TxtCartaoJogador2.getText()), cartaoVermelho(CheckCartaoVermelhorJogador2), codc, codJogo);
//                sbjj.insert(jogador2);
//                Jogadores_Jogo jogador3 = new Jogadores_Jogo(Integer.parseInt(TxtGolJogador3.getText()), Integer.parseInt(TxtCartaoJogador3.getText()), cartaoVermelho(CheckCartaoVermelhorJogador3), codd, codJogo);
//                sbjj.insert(jogador3);
//                Jogadores_Jogo jogador4 = new Jogadores_Jogo(Integer.parseInt(TxtGolJogador4.getText()), Integer.parseInt(TxtCartaoJogador4.getText()), cartaoVermelho(CheckCartaoVermelhorJogador4), code, codJogo);
//                sbjj.insert(jogador4);
                Jogadores_Jogo jogador5 = new Jogadores_Jogo(Integer.parseInt(TxtGolFora.getText()), Integer.parseInt(TxtCartaoFora.getText()), cartaoVermelho(CheckCartaoVermelhorJogadorFora), codf, codJogo);
                sbjj.insert(jogador5);
//                Jogadores_Jogo jogador6 = new Jogadores_Jogo(Integer.parseInt(TxtGolFora1.getText()), Integer.parseInt(TxtCartaoFora1.getText()), cartaoVermelho(CheckCartaoVermelhorJogadorFora1), codg, codJogo);
//                sbjj.insert(jogador6);
//                Jogadores_Jogo jogador7 = new Jogadores_Jogo(Integer.parseInt(TxtGolFora2.getText()), Integer.parseInt(TxtCartaoFora2.getText()), cartaoVermelho(CheckCartaoVermelhorJogadorFora2), codh, codJogo);
//                sbjj.insert(jogador7);
//                Jogadores_Jogo jogador8 = new Jogadores_Jogo(Integer.parseInt(TxtGolFora3.getText()), Integer.parseInt(TxtCartaoFora3.getText()), cartaoVermelho(CheckCartaoVermelhorJogadorFora3), codi, codJogo);
//                sbjj.insert(jogador8);
//                Jogadores_Jogo jogador9 = new Jogadores_Jogo(Integer.parseInt(TxtGolFora4.getText()), Integer.parseInt(TxtCartaoFora4.getText()), cartaoVermelho(CheckCartaoVermelhorJogadorFora4), codj, codJogo);
//                sbjj.insert(jogador9);

                JOptionPane.showMessageDialog(
                        null, "Cadastrado com sucesso",
                        "Cadastro!!!", JOptionPane.INFORMATION_MESSAGE,
                        new ImageIcon("C:\\Users\\PremierSoft\\IdeaProjects\\Campeonatos_Futebol\\src\\View\\Cadastro.gif"));

            }

            if (ComboCampeonato.getSelectedIndex() >= 0) {
                Campeonato campeonato = (Campeonato) ComboCampeonato.getSelectedItem();
                assert campeonato != null;
                campeonato.setNome(ComboCampeonato.getSelectedItem().toString());
                sbcam.update(campeonato);
                jogo = new Jogo(campeonato.getCodigo(), utils.strToDate(TxtDiaJogo.getText()), utils.strToTime(TxtHoraJogo.getText()), clubeTemp, Integer.parseInt(TxtGolJogador.getText()), clubee.getCodigo(), Integer.parseInt(TxtGolFora.getText()), TxtLocalJogo.getText());
                sbj.insert(jogo);

            }

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ParseException ex) {
            Logger.getLogger(Cadastro_Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JbtnSalvarMouseClicked


    private void JBtnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtnSairMouseClicked
        dispose();
    }//GEN-LAST:event_JBtnSairMouseClicked

    private void JBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLimparActionPerformed
        this.clearSc();
    }//GEN-LAST:event_JBtnLimparActionPerformed

    private void ComboCampeonatoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCampeonatoItemStateChanged
        if (ComboCampeonato.getItemCount() <= 0) {
            return;
        }
        if (ComboCampeonato.getSelectedIndex() < 0) {
            return;
        }
        TxtDiaJogo.setText(utils.converterData());
        TxtHoraJogo.setText(utils.converterHora());
        Campeonato categoria = (Campeonato) ComboCampeonato.getSelectedItem();
        assert categoria != null;
        JBtnLimpar.setEnabled(true);

    }//GEN-LAST:event_ComboCampeonatoItemStateChanged

    public int gols(JTextField g, JTextField g1, JTextField g2, JTextField g3, JTextField g4) {
        int gc = 0, gc1 = 0, gc2 = 0, gc3 = 0, gc4 = 0;
        if (!g.getText().isBlank()) {
            gc = Integer.parseInt(g.getText());
        }
        if (!g1.getText().isBlank()) {
            gc1 = Integer.parseInt(g1.getText());
        }
        if (!g2.getText().isBlank()) {
            gc2 = Integer.parseInt(g2.getText());
        }
        if (!g3.getText().isBlank()) {
            gc3 = Integer.parseInt(g3.getText());
        }
        if (!g4.getText().isBlank()) {
            gc4 = Integer.parseInt(g4.getText());
        }
        return gc + gc1 + gc2 + gc3 + gc4;
    }

    private void JrFimPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JrFimPartidaMouseClicked

        if (JrFimPartida.isEnabled()) {
            LbPlacarMandante.setText(String.valueOf(this.gols(TxtGolJogador, TxtGolJogador1, TxtGolJogador2, TxtGolJogador3, TxtGolJogador4)));
            LbPlacarVisitante.setText(String.valueOf(this.gols(TxtGolFora, TxtGolFora1, TxtGolFora2, TxtGolFora3, TxtGolFora4)));
        }
    }//GEN-LAST:event_JrFimPartidaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            utils.atualizarCampeonato(ComboCampeonato, sbcam);
            utils.atualizarClube(ComboClube, sbc);
            utils.atualizarClube(ComboClube1, sbc);
            utils.setGols(TxtGolFora, TxtGolFora1, TxtGolFora2, TxtGolFora3, TxtGolFora4, TxtGolJogador, TxtGolJogador1, TxtGolJogador2, TxtGolJogador3, TxtGolJogador4);
            utils.setCartoes(TxtCartaoFora1, TxtCartaoFora2, TxtCartaoFora3, TxtCartaoFora4, TxtCartaoFora, TxtCartaoJogador, TxtCartaoJogador1, TxtCartaoJogador2, TxtCartaoJogador3, TxtCartaoJogador4);
            utils.atualizarJogador(JComboJogadorCasa, sbjogador);
            this.clearSc();

        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Campeonato.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void JComboJogadorForaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JComboJogadorForaMouseClicked
        if (JComboJogadorFora.getItemCount() <= 0) {
            return;
        }
        if (JComboJogadorFora.getSelectedIndex() < 0) {
            return;
        }
        Jogador jogador = (Jogador) JComboJogadorFora.getSelectedItem();
        assert jogador != null;
        try {
            sbjogador.update(jogador);
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Jogo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        if (TxtJogadorFora.getText().isBlank()) {
            TxtJogadorFora.setText(jogador.getNome());
            codf = jogador.getCodigo();

        } else if (TxtJogadorFora1.getText().isBlank()) {
            TxtJogadorFora1.setText(jogador.getNome());
            codg = jogador.getCodigo();

        } else if (TxtJogadorFora2.getText().isBlank()) {
            TxtJogadorFora2.setText(jogador.getNome());
            codh = jogador.getCodigo();
        } else if (TxtJogadorFora3.getText().isBlank()) {
            TxtJogadorFora3.setText(jogador.getNome());
            codi = jogador.getCodigo();
        } else {
            TxtJogadorFora4.setText(jogador.getNome());
            codj = jogador.getCodigo();
        }
        JComboJogadorCasa.setSelectedIndex(-1);
    }//GEN-LAST:event_JComboJogadorForaMouseClicked

    private void TxtCartaoJogadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoJogadorFocusLost
        contarCartao(TxtCartaoJogador, CheckCartaoVermelhorJogador);
    }//GEN-LAST:event_TxtCartaoJogadorFocusLost

    private void TxtCartaoJogador1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoJogador1FocusLost
        contarCartao(TxtCartaoJogador1, CheckCartaoVermelhorJogador1);
    }//GEN-LAST:event_TxtCartaoJogador1FocusLost

    private void TxtCartaoJogador2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoJogador2FocusLost
        contarCartao(TxtCartaoJogador2, CheckCartaoVermelhorJogador2);
    }//GEN-LAST:event_TxtCartaoJogador2FocusLost

    private void TxtCartaoJogador3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoJogador3FocusLost
        contarCartao(TxtCartaoJogador3, CheckCartaoVermelhorJogador3);
    }//GEN-LAST:event_TxtCartaoJogador3FocusLost

    private void TxtCartaoJogador4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoJogador4FocusLost
        contarCartao(TxtCartaoJogador4, CheckCartaoVermelhorJogador4);
    }//GEN-LAST:event_TxtCartaoJogador4FocusLost

    private void TxtCartaoForaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoForaFocusLost
        contarCartao(TxtCartaoFora, CheckCartaoVermelhorJogadorFora);
    }//GEN-LAST:event_TxtCartaoForaFocusLost

    private void TxtCartaoFora1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoFora1FocusLost
        contarCartao(TxtCartaoFora1, CheckCartaoVermelhorJogadorFora1);
    }//GEN-LAST:event_TxtCartaoFora1FocusLost

    private void TxtCartaoFora2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoFora2FocusLost
        contarCartao(TxtCartaoFora2, CheckCartaoVermelhorJogadorFora2);
    }//GEN-LAST:event_TxtCartaoFora2FocusLost

    private void TxtCartaoFora3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoFora3FocusLost
        contarCartao(TxtCartaoFora3, CheckCartaoVermelhorJogadorFora3);
    }//GEN-LAST:event_TxtCartaoFora3FocusLost

    private void TxtCartaoFora4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCartaoFora4FocusLost
        contarCartao(TxtCartaoFora4, CheckCartaoVermelhorJogadorFora4);
    }//GEN-LAST:event_TxtCartaoFora4FocusLost

    private void CheckCartaoVermelhorJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCartaoVermelhorJogadorActionPerformed
        cartaoVermelho(CheckCartaoVermelhorJogador);
    }//GEN-LAST:event_CheckCartaoVermelhorJogadorActionPerformed

    public void novoClube() {
        if (cadastro_Clube == null) {
            cadastro_Clube = new Cadastro_Clube();
        }
        cadastro_Clube.setVisible(true);
    }
    private void TxtNovoClubeMandanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNovoClubeMandanteMouseClicked
        this.novoClube();
    }//GEN-LAST:event_TxtNovoClubeMandanteMouseClicked

    private void TxtNovoClube1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNovoClube1MouseClicked
        this.novoClube();
    }//GEN-LAST:event_TxtNovoClube1MouseClicked

    private void JComboJogadorCasaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboJogadorCasaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboJogadorCasaItemStateChanged

    private void contarCartao(JTextField cardAmar, JCheckBox cardVer) {
        if (!cardAmar.getText().isBlank() && Integer.parseInt(cardAmar.getText()) >= 2) {
            cardVer.setSelected(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadastro_Jogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckCartaoVermelhorJogador;
    private javax.swing.JCheckBox CheckCartaoVermelhorJogador1;
    private javax.swing.JCheckBox CheckCartaoVermelhorJogador2;
    private javax.swing.JCheckBox CheckCartaoVermelhorJogador3;
    private javax.swing.JCheckBox CheckCartaoVermelhorJogador4;
    private javax.swing.JCheckBox CheckCartaoVermelhorJogadorFora;
    private javax.swing.JCheckBox CheckCartaoVermelhorJogadorFora1;
    private javax.swing.JCheckBox CheckCartaoVermelhorJogadorFora2;
    private javax.swing.JCheckBox CheckCartaoVermelhorJogadorFora3;
    private javax.swing.JCheckBox CheckCartaoVermelhorJogadorFora4;
    private javax.swing.JComboBox<Campeonato> ComboCampeonato;
    private javax.swing.JComboBox<Clube> ComboClube;
    private javax.swing.JComboBox<Clube> ComboClube1;
    private javax.swing.JButton JBtnLimpar;
    private javax.swing.JButton JBtnSair;
    private javax.swing.JComboBox<Jogador> JComboJogadorCasa;
    private javax.swing.JComboBox<Jogador> JComboJogadorFora;
    private javax.swing.JButton JbtnSalvar;
    private javax.swing.JRadioButton JrFimPartida;
    private javax.swing.JLabel LbCat;
    private javax.swing.JLabel LbDiaJogo;
    private javax.swing.JLabel LbHoraJogo;
    private javax.swing.JLabel LbJogadores;
    private javax.swing.JLabel LbJogadores1;
    private javax.swing.JLabel LbLocalJogo;
    private javax.swing.JLabel LbMandante;
    private javax.swing.JTextField LbPlacarMandante;
    private javax.swing.JTextField LbPlacarVisitante;
    private javax.swing.JLabel LbVisitante;
    private javax.swing.JTextField TxtCartaoFora;
    private javax.swing.JTextField TxtCartaoFora1;
    private javax.swing.JTextField TxtCartaoFora2;
    private javax.swing.JTextField TxtCartaoFora3;
    private javax.swing.JTextField TxtCartaoFora4;
    private javax.swing.JTextField TxtCartaoJogador;
    private javax.swing.JTextField TxtCartaoJogador1;
    private javax.swing.JTextField TxtCartaoJogador2;
    private javax.swing.JTextField TxtCartaoJogador3;
    private javax.swing.JTextField TxtCartaoJogador4;
    private javax.swing.JFormattedTextField TxtDiaJogo;
    private javax.swing.JTextField TxtGolFora;
    private javax.swing.JTextField TxtGolFora1;
    private javax.swing.JTextField TxtGolFora2;
    private javax.swing.JTextField TxtGolFora3;
    private javax.swing.JTextField TxtGolFora4;
    private javax.swing.JTextField TxtGolJogador;
    private javax.swing.JTextField TxtGolJogador1;
    private javax.swing.JTextField TxtGolJogador2;
    private javax.swing.JTextField TxtGolJogador3;
    private javax.swing.JTextField TxtGolJogador4;
    private javax.swing.JFormattedTextField TxtHoraJogo;
    private javax.swing.JTextField TxtJogador;
    private javax.swing.JTextField TxtJogador1;
    private javax.swing.JTextField TxtJogador2;
    private javax.swing.JTextField TxtJogador3;
    private javax.swing.JTextField TxtJogador4;
    private javax.swing.JTextField TxtJogadorFora;
    private javax.swing.JTextField TxtJogadorFora1;
    private javax.swing.JTextField TxtJogadorFora2;
    private javax.swing.JTextField TxtJogadorFora3;
    private javax.swing.JTextField TxtJogadorFora4;
    private javax.swing.JTextField TxtLocalJogo;
    private javax.swing.JButton TxtNovoClube1;
    private javax.swing.JButton TxtNovoClubeMandante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
