/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Clubes_Campeonatos.Campeonato;
import Clubes_Campeonatos.Clube;
import Clubes_Campeonatos.Utils;
import Controller.ServicoBancoCampeonato;
import Controller.ServicoBancoClube;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PremierSoft
 */
public class Cadastro_Jogo extends javax.swing.JFrame {
    Utils utils = new Utils();
    ServicoBancoCampeonato sbcam = new ServicoBancoCampeonato();
    ServicoBancoClube sbc = new ServicoBancoClube();
    Campeonato campeonato = new Campeonato();
    Clube clube = new Clube();

    /**
     * Creates new form Cadastro_Jogo
     */
    public Cadastro_Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LbCat = new javax.swing.JLabel();
        ComboCampeonato = new javax.swing.JComboBox<>();
        TxtCampeonato = new javax.swing.JTextField();
        LbDiaJogo = new javax.swing.JLabel();
        TxtDiaJogo = new javax.swing.JTextField();
        LbHoraJogo = new javax.swing.JLabel();
        TxtHoraJogo = new javax.swing.JTextField();
        TxtTimeFora = new javax.swing.JTextField();
        TxtGolCasa = new javax.swing.JTextField();
        TxtTimeCasa = new javax.swing.JTextField();
        TxtGolsFora = new javax.swing.JTextField();
        ComboClube = new javax.swing.JComboBox<>();
        ComboClube1 = new javax.swing.JComboBox<>();
        LbLocalJogo = new javax.swing.JLabel();
        TxtLocalJogo = new javax.swing.JTextField();
        JbtnSalvar = new javax.swing.JButton();
        JBtnSair = new javax.swing.JButton();
        JBtnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MingLiU-ExtB", 0, 18)); // NOI18N
        jLabel1.setText("CADASTRAR JOGOS...");

        LbCat.setText("CAMPEONATO");

        ComboCampeonato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCampeonatoItemStateChanged(evt);
            }
        });
        ComboCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCampeonatoActionPerformed(evt);
            }
        });

        TxtCampeonato.setMaximumSize(new java.awt.Dimension(35, 16));
        TxtCampeonato.setMinimumSize(new java.awt.Dimension(35, 16));
        TxtCampeonato.setName(""); // NOI18N
        TxtCampeonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCampeonatoActionPerformed(evt);
            }
        });

        LbDiaJogo.setText("DIA DO JOGO");

        TxtDiaJogo.setMaximumSize(new java.awt.Dimension(35, 16));
        TxtDiaJogo.setMinimumSize(new java.awt.Dimension(35, 16));
        TxtDiaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDiaJogoActionPerformed(evt);
            }
        });

        LbHoraJogo.setText("HORA DO JOGO");

        TxtHoraJogo.setMaximumSize(new java.awt.Dimension(35, 16));
        TxtHoraJogo.setMinimumSize(new java.awt.Dimension(35, 16));
        TxtHoraJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHoraJogoActionPerformed(evt);
            }
        });

        TxtTimeFora.setText("TIME VISITANTE");

        TxtGolCasa.setText("GOLS");

        TxtTimeCasa.setText("TIME DA CASA");

        TxtGolsFora.setText("GOLS");
        TxtGolsFora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGolsForaActionPerformed(evt);
            }
        });

        ComboClube.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ComboClube.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboClubeItemStateChanged(evt);
            }
        });

        ComboClube1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ComboClube1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboClube1ItemStateChanged(evt);
            }
        });

        LbLocalJogo.setText("LOCAL DO JOGO");

        TxtLocalJogo.setMaximumSize(new java.awt.Dimension(35, 16));
        TxtLocalJogo.setMinimumSize(new java.awt.Dimension(35, 16));
        TxtLocalJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLocalJogoActionPerformed(evt);
            }
        });

        JbtnSalvar.setText("SALVAR");
        JbtnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JbtnSalvarMouseClicked(evt);
            }
        });

        JBtnSair.setText("SAIR");
        JBtnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtnSairMouseClicked(evt);
            }
        });

        JBtnLimpar.setText("LIMPAR");
        JBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LbDiaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtDiaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LbHoraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxtTimeCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtHoraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(TxtGolCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(TxtTimeFora, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(TxtGolsFora, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ComboClube, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(ComboClube1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbLocalJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JbtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtLocalJogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JBtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(LbCat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboCampeonato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtCampeonato, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDiaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDiaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbHoraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtHoraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTimeFora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtGolCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTimeCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtGolsFora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboClube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboClube1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbLocalJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtLocalJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboCampeonatoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCampeonatoItemStateChanged

        if (ComboCampeonato.getItemCount()<=0) {
            return;
        }
        if (ComboCampeonato.getSelectedIndex()<0) {
            return;
        }
        Campeonato categoria = (Campeonato) ComboCampeonato.getSelectedItem();
        TxtCampeonato.setText(categoria.getNome());
    }//GEN-LAST:event_ComboCampeonatoItemStateChanged

    private void ComboCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCampeonatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCampeonatoActionPerformed

    private void TxtCampeonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCampeonatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCampeonatoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            utils.atualizarCampeonato(ComboCampeonato, sbcam);
            utils.atualizarClube(ComboClube, sbc);
            utils.atualizarClube(ComboClube1, sbc);
//            clearSc();

        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Campeonato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void TxtDiaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDiaJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDiaJogoActionPerformed

    private void TxtHoraJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHoraJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHoraJogoActionPerformed

    private void ComboClubeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboClubeItemStateChanged

        if (ComboClube.getItemCount()<=0) {
            return;
        }
        if (ComboClube.getSelectedIndex()<0) {
            return;
        }
        Clube clube = (Clube) ComboClube.getSelectedItem();
        TxtTimeCasa.setText(clube.getNome());

    }//GEN-LAST:event_ComboClubeItemStateChanged

    private void ComboClube1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboClube1ItemStateChanged

        if (ComboClube1.getItemCount()<=0) {
            return;
        }
        if (ComboClube1.getSelectedIndex()<0) {
            return;
        }
        Clube clube = (Clube) ComboClube1.getSelectedItem();
        TxtTimeFora.setText(clube.getNome());

    }//GEN-LAST:event_ComboClube1ItemStateChanged

    private void TxtGolsForaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGolsForaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGolsForaActionPerformed

    private void TxtLocalJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLocalJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLocalJogoActionPerformed

    private void JbtnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbtnSalvarMouseClicked
//        if (TxtNome.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"Informe um nome!");
//            TxtNome.requestFocus();
//            return;
//        }
//        if (TxtMAscote.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"Informe um nome de mascote!");
//            TxtCategoria.requestFocus();
//            return;
//
//        }
//        if (TxtCategoria.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"Informe uma categoria!");
//            TxtNome.requestFocus();
//            return;
//        }
//
//        try {
//            if (ComboCampeonato.getSelectedIndex() >= 0) {
//
//                Categoria categoria = (Categoria) ComboCampeonato.getSelectedItem();
//                categoria.setNome(TxtCategoria.getText());
//                sbcat.update(categoria);
//
//                clube = new Clube(TxtNome.getText(),TxtMAscote.getText(),categoria.getCodigo());
//                sb.insert(clube);
//            } else
//            categoria = new Categoria(TxtCategoria.getText());
//            sbcat.insert(categoria);
//
//            clube = new Clube(TxtNome.getText(),TxtMAscote.getText(),categoria.getCodigo());
//            clube = new Clube(TxtNome.getText(),TxtMAscote.getText(),categoria.getCodigo());
//            sb.insert(clube);
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_JbtnSalvarMouseClicked

    private void JBtnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtnSairMouseClicked
        dispose();
    }//GEN-LAST:event_JBtnSairMouseClicked

    private void JBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Campeonato> ComboCampeonato;
    private javax.swing.JComboBox<Clube> ComboClube;
    private javax.swing.JComboBox<Clube> ComboClube1;
    private javax.swing.JButton JBtnLimpar;
    private javax.swing.JButton JBtnSair;
    private javax.swing.JButton JbtnSalvar;
    private javax.swing.JLabel LbCat;
    private javax.swing.JLabel LbDiaJogo;
    private javax.swing.JLabel LbHoraJogo;
    private javax.swing.JLabel LbLocalJogo;
    private javax.swing.JTextField TxtCampeonato;
    private javax.swing.JTextField TxtDiaJogo;
    private javax.swing.JTextField TxtGolCasa;
    private javax.swing.JTextField TxtGolsFora;
    private javax.swing.JTextField TxtHoraJogo;
    private javax.swing.JTextField TxtLocalJogo;
    private javax.swing.JTextField TxtTimeCasa;
    private javax.swing.JTextField TxtTimeFora;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
