/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Clubes_Campeonatos.Campeonato;
import Clubes_Campeonatos.Categoria;
import java.sql.SQLException;
import Clubes_Campeonatos.Utils;
import Controller.ServicoBancoCampeonato;
import Controller.ServicoBancoCategoria;
import java.text.ParseException;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author PremierSoft
 */
public class Consulta_Campeonato extends javax.swing.JFrame {

    Campeonato campeonato = new Campeonato();
    private Categoria categoria = new Categoria();
    Utils utils = new Utils();
    ServicoBancoCampeonato sb = new ServicoBancoCampeonato();
    ServicoBancoCategoria sbcat = new ServicoBancoCategoria();

    public Consulta_Campeonato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LbNome = new javax.swing.JLabel();
        LbDataInicio = new javax.swing.JLabel();
        LbDataFim = new javax.swing.JLabel();
        LbCategoria = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        TxtCategoria = new javax.swing.JTextField();
        JBtnLimpar = new javax.swing.JButton();
        JBtnSair = new javax.swing.JButton();
        JBtnSalvar = new javax.swing.JButton();
        TxtDataInicio = new javax.swing.JFormattedTextField();
        TxtDataFim = new javax.swing.JFormattedTextField();
        ComboCampeonato = new javax.swing.JComboBox<>();
        ComboCategoria2 = new javax.swing.JComboBox<>();
        JbExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        MenuConsultas = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(-1);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MingLiU-ExtB", 0, 18)); // NOI18N
        jLabel1.setText("CADASTRAR CAMPEONATOS...");

        LbNome.setText("NOME");

        LbDataInicio.setText("INICIO DO CAMPEONATO");

        LbDataFim.setText("FIM DO CAMPEONATO");

        LbCategoria.setText("CATEGORIA");

        TxtNome.setEditable(false);

        TxtCategoria.setEditable(false);

        JBtnLimpar.setText("LIMPAR");
        JBtnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtnLimparMouseClicked(evt);
            }
        });
        JBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLimparActionPerformed(evt);
            }
        });

        JBtnSair.setText("SAIR");
        JBtnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtnSairMouseClicked(evt);
            }
        });

        JBtnSalvar.setText("SALVAR");
        JBtnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtnSalvarMouseClicked(evt);
            }
        });

        TxtDataInicio.setEditable(false);
        try {
            TxtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TxtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ComboCampeonato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCampeonatoItemStateChanged(evt);
            }
        });

        ComboCategoria2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCategoria2ItemStateChanged(evt);
            }
        });

        JbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/lixo.png"))); // NOI18N
        JbExcluir.setBorder(null);
        JbExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JbExcluirMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/cONSULTAS.gif"))); // NOI18N

        MenuCadastros.setText("Cadastros");
        jMenuBar1.add(MenuCadastros);

        MenuConsultas.setText("Consultas");
        jMenuBar1.add(MenuConsultas);

        MenuSair.setText("Sair");
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDataInicio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDataFim))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBtnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(JBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboCampeonato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboCategoria2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboCampeonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLimparActionPerformed
        this.clearSc();
    }//GEN-LAST:event_JBtnLimparActionPerformed
    public void clearSc() {
        if (ComboCampeonato.isDisplayable()) {
            ComboCampeonato.setSelectedIndex(-1);
        }
        TxtNome.setText("");
        TxtDataInicio.setText("");
        TxtDataFim.setText("");
        TxtCategoria.setText("");
        TxtNome.requestFocus();
        JBtnLimpar.setEnabled(false);

    }

    private void cadastrarCategoria() {
        try {
            if (ComboCampeonato.getSelectedIndex() >= 0) {

                Categoria categoria = (Categoria) ComboCampeonato.getSelectedItem();
                assert categoria != null;
                categoria.setNome(TxtCategoria.getText());
                sbcat.update(categoria);

            } else {
                Categoria categoria = new Categoria(TxtCategoria.getText());
                sbcat.insert(categoria);
            }
            clearSc();
            utils.atualizarCampeonato(ComboCampeonato, sb);

        } catch (SQLException ex) {
            Logger.getLogger(Consulta_Campeonato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void JBtnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtnSalvarMouseClicked

        if (TxtDataInicio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a nova data final do campeonato!");
            TxtCategoria.requestFocus();
            return;

        }

        try {
            if (ComboCategoria2.getSelectedIndex() >= 0) {

                Categoria categoria = (Categoria) ComboCategoria2.getSelectedItem();
                assert categoria != null;
                categoria.setNome(TxtCategoria.getText());
                sbcat.update(categoria);
                if (ComboCampeonato.getSelectedIndex() >= 0) {
                    campeonato.setDataFim(utils.strToDate(TxtDataFim.getText()));
                    sb.update(campeonato);
                    JOptionPane.showMessageDialog(
                            null, "Alterado com sucesso",
                            "Cadastro!!!", JOptionPane.INFORMATION_MESSAGE,
                            new ImageIcon("C:\\Users\\PremierSoft\\IdeaProjects\\Campeonatos_Futebol\\src\\View\\Cadastro.gif"));
                    clearSc();
                }

            }
//            else 
//            {
//                categoria = new Categoria(TxtCategoria.getText());
//            }
//            sbcat.insert(categoria);
//
//            campeonato = new Campeonato(TxtNome.getText(), utils.strToDate(TxtDataInicio.getText()), utils.strToDate(TxtDataFim.getText()), categoria.getCodigo());
//            sb.insert(campeonato);
        } catch (SQLException ignored) {
        } catch (ParseException ex) {
            Logger.getLogger(Consulta_Campeonato.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_JBtnSalvarMouseClicked

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        dispose();
    }//GEN-LAST:event_MenuSairMouseClicked

    private void JBtnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtnSairMouseClicked
        dispose();
    }//GEN-LAST:event_JBtnSairMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            utils.atualizarCategoria(ComboCategoria2, sbcat);
            utils.atualizarCampeonato(ComboCampeonato, sb);

            clearSc();

        } catch (SQLException ex) {
            Logger.getLogger(Consulta_Campeonato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void JBtnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtnLimparMouseClicked
        clearSc();
    }//GEN-LAST:event_JBtnLimparMouseClicked

    private void ComboCampeonatoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCampeonatoItemStateChanged
        if (ComboCampeonato.getItemCount() <= 0) {
            return;
        }
        if (ComboCampeonato.getSelectedIndex() < 0) {
            return;
        }
        campeonato = (Campeonato) ComboCampeonato.getSelectedItem();
        assert campeonato != null;
        TxtNome.setText(campeonato.getNome());
        TxtDataFim.setText(utils.getDataFormatada(campeonato.getDataFim()));
        TxtDataInicio.setText(utils.getDataFormatada(campeonato.getDataInicio()));

        JBtnLimpar.setEnabled(true);

    }//GEN-LAST:event_ComboCampeonatoItemStateChanged

    private void ComboCategoria2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCategoria2ItemStateChanged

        if (ComboCategoria2.getItemCount() <= 0) {
            return;
        }
        if (ComboCategoria2.getSelectedIndex() < 0) {
            return;
        }
        Categoria categoria = (Categoria) ComboCategoria2.getSelectedItem();
        assert categoria != null;
        TxtCategoria.setText(categoria.getNome());
        JBtnLimpar.setEnabled(true);

        try {
            utils.atualizarCampeonatoByCategoria(ComboCampeonato, sb, categoria.getCodigo());
        } catch (SQLException ex) {
            Logger.getLogger(Consulta_Campeonato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboCategoria2ItemStateChanged

    private void JbExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbExcluirMouseClicked
        if (ComboCampeonato.getItemCount() <= 0) {
            return;
        }
        if (ComboCampeonato.getSelectedIndex() < 0) {
            return;
        }
        Campeonato campeonato = (Campeonato) ComboCampeonato.getSelectedItem();
        assert campeonato != null;
        TxtCategoria.setText(categoria.getNome());
        JBtnLimpar.setEnabled(true);
        int del = JOptionPane.showConfirmDialog(null, "Você deseja realmente excluir o registro " + campeonato, "Excluir...",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, new ImageIcon("C:\\Users\\PremierSoft\\IdeaProjects\\Campeonatos_Futebol\\src\\View\\delete.gif"));
        if (del == JOptionPane.YES_OPTION) {
            try {
                sb.delete(campeonato);
                utils.atualizarCampeonato(ComboCampeonato, sb);
                clearSc();
            } catch (SQLException ex) {
                Logger.getLogger(Consulta_Clube.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(
                    null, "Excluido com sucesso",
                    "Cadastro!!!", JOptionPane.INFORMATION_MESSAGE,
                    new ImageIcon("C:\\Users\\PremierSoft\\IdeaProjects\\Campeonatos_Futebol\\src\\View\\deleted.gif"));
        } else if (del == JOptionPane.NO_OPTION) {
            clearSc();
        }

    }//GEN-LAST:event_JbExcluirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | InstantiationException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_Campeonato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta_Campeonato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Campeonato> ComboCampeonato;
    private javax.swing.JComboBox<Categoria> ComboCategoria2;
    private javax.swing.JButton JBtnLimpar;
    private javax.swing.JButton JBtnSair;
    private javax.swing.JButton JBtnSalvar;
    private javax.swing.JButton JbExcluir;
    private javax.swing.JLabel LbCategoria;
    private javax.swing.JLabel LbDataFim;
    private javax.swing.JLabel LbDataInicio;
    private javax.swing.JLabel LbNome;
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenu MenuConsultas;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JTextField TxtCategoria;
    private javax.swing.JFormattedTextField TxtDataFim;
    private javax.swing.JFormattedTextField TxtDataInicio;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
