package View;

import Controller.ServicoBancoCampeonato;
import Controller.ServicoBancoClubeCampeonato;
import Controller.ServicoBancoJogador;
import Controller.SimpleTableModel;

import javax.swing.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PremierSoft
 */
public class Consulta_Dados extends javax.swing.JFrame {

    private ServicoBancoJogador sbj = new ServicoBancoJogador();
    private ServicoBancoClubeCampeonato sbcc = new ServicoBancoClubeCampeonato();

    public Consulta_Dados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDados = new javax.swing.JTable();
        ComboFiltro = new javax.swing.JComboBox<>();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MingLiU-ExtB", 0, 18)); // NOI18N
        jLabel1.setText("STATUS DOS CAMPEONATOS!!!");

        TableDados.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDados.setEnabled(false);
        TableDados.setGridColor(new java.awt.Color(51, 255, 51));
        jScrollPane1.setViewportView(TableDados);

        ComboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O time com mais Jogadores Cadastrados", "O time com mais gols feitos", "O time com menos gols sofridos", "O time com mais cartões amarelos", "Item 3", "Item 4" }));
        ComboFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboFiltroItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ComboFiltro, 0, 284, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboFiltroItemStateChanged
        if (ComboFiltro.getItemCount() <= 0) {
            return;
        }
        if (ComboFiltro.getSelectedIndex() < 0) {
            return;
        }
        if (ComboFiltro.getSelectedIndex() == 0) {
            this.carregarTabelaOrderByQtdJogadores();

        } else if (ComboFiltro.getSelectedIndex() == 1) {
            this.carregarTabelaByGolsPro();
            
        } else if (ComboFiltro.getSelectedIndex() == 2) {
            this.carregarTabelaByGolsContra();
        }
    }//GEN-LAST:event_ComboFiltroItemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        this.carregarTabelaOrderByQtdJogadores();
    }//GEN-LAST:event_formWindowActivated

    public void carregarTabelaOrderByQtdJogadores() {
        ArrayList dados;
        try {
            dados = sbj.getTabelaByQuery();
            String[] colunas = new String[]{
                "Clube",
                "Quantidade de \n jogadores"

            };
            SimpleTableModel tabela = new SimpleTableModel(dados, colunas);
            TableDados.setModel(tabela);
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(Consulta_Dados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void carregarTabelaByGolsPro() {

        ArrayList dados;
        try {
            dados = sbcc.getTabelaByQueryOrderByGoals();
            String[] colunas = new String[]{
                "nome",
                "Vitória",
                "Derrota",
                "Empate",
                "Gols Pró",
                "Gols Contra",
                "Cartões Amarelo",
                "Cartões Vermelho"

            };
            SimpleTableModel tabela = new SimpleTableModel(dados, colunas);
            TableDados.setModel(tabela);

        } catch (SQLException ex) {
            Logger.getLogger(Consulta_Dados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void carregarTabelaByGolsContra() {

        ArrayList dados;
        try {
            dados = sbcc.getTabelaByQueryOrderByGoalsContra();
            String[] colunas = new String[]{
                "nome",
                "Vitória",
                "Derrota",
                "Empate",
                "Gols Pró",
                "Gols Contra",
                "Cartões Amarelo",
                "Cartões Vermelho"

            };
            SimpleTableModel tabela = new SimpleTableModel(dados, colunas);
            TableDados.setModel(tabela);

        } catch (SQLException ex) {
            Logger.getLogger(Consulta_Dados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Consulta_Dados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboFiltro;
    private javax.swing.JTable TableDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
